# Numpy Task

### Instructions:
- Answer the following questions using NumPy only.
- Do not use Python loops unless explicitly stated.

## Part 1: Creating Arrays (3 Questions)


####  1) Create a NumPy array that contains all even numbers between 10 and 50 (inclusive).


In [2]:
import numpy as np
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]





#### 2) Create an array of shape (3, 4) filled with ones, then change all values in the last column to 0.



In [3]:
arr=np.ones((3,4))
print(arr)
arr[:,-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]





#### 3) Create a NumPy array of 5 equally spaced numbers between -1 and 1.

In [4]:
arr=np.linspace(-1,1,5)
print(arr)

[-1.  -0.5  0.   0.5  1. ]


## Part 2: Array Properties (3 Questions)

#### 1) Create array and then 
- Find its shape

- Number of elements

- Data type

In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(2, 3)
6
int64


#### 2) Create a random array of size 10 and find:
- minimum value

- maximum value

- standard deviation

In [6]:
arr=np.random.randint(1,100,size=10)
print(arr)
print(arr.min())
print(arr.max())
print(arr.std())

[69 31 96 52  7 34 95  5 91 46]
5
96
32.59815945724543


#### 3) What is the difference between arr.size and arr.shape?

- Explain using an example.

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size) #number of elements in array
print(arr.shape) #number of rows and columns (rows*columns)

6
(2, 3)


## Part 3: Mathematical Operations & ufuncs (3 Questions)

#### 1) Create a new array that contains the square of each element without using loops.

In [8]:
# Given 

arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]


#### 2) Compute the mean and sum of all values in a 3×3 random matrix.

In [9]:
arr=np.random.randint(1,100,size=(3,3))
print(arr)
print(np.mean(arr))
print(np.sum(arr))

[[79 52 22]
 [74 85 57]
 [37 31 85]]
58.0
522


#### 3) Compute the mean and sum of all values in a 3×3 random matrix.

In [10]:
arr=np.random.randint(1,100,size=(3,3))
print(arr)
print(np.mean(arr))
print(np.sum(arr))

[[16 84 24]
 [ 3 83  9]
 [61 40 36]]
39.55555555555556
356


## Part 4: Indexing, Slicing & Boolean Indexing (4 Questions)

#### 1) Extract the middle four elements using slicing.

In [11]:
# Given 
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5])


[20 30 40 50]


#### 2) From the same array, extract all values greater than 25.

In [12]:
print(arr[arr>25])

[30 40 50 60]


#### 3) Modify the array so that all values less than 30 become 0.

In [13]:
arr[arr<30]=0
print(arr)

[ 0  0 30 40 50 60]


#### 4) When would slicing be better than Boolean indexing?
Give one example.

In [26]:
#لما أكون عارفة مكان العناصر اللى أنا عايزاها
#لما أكون محتاجه جزء معينة من المصفوفة وعاوزاه ورا بعض من غير ما نسيب عناصر فى النص

## Part 5: Random Numbers & Performance (3 Questions)

#### 1) Generate a reproducible array of 15 random integers between 1 and 100.

In [14]:
arr=np.random.randint(1,100,size=15)
print(arr)

[40 76 21 69 33 59 64 83 81 67 28 48 86  6 24]


#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization 

``to add 10 to each element.``

**Which one is faster and why?**

In [15]:
#using Numpy
numpy_arr=np.arange(1,10)
print(numpy_arr)
print(numpy_arr+10)

#using python
python_arr=[1,2,3,4,5,6,7,8,9]
print(python_arr)
for n in python_arr:
    print(n+10)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
11
12
13
14
15
16
17
18
19


In [16]:
# Numpy is faster than python 
#because numpy use vectorize to perform operations (بتعملها مرة واحدة)
#but python makes loops to perform operation on element by element

#### 4) Why is `np.random.seed()` important in data science experiments?

In [17]:
#seed() ===> to use same random numbers
#ده هيخلى النواتج تطلع واحدة حتى إن  رنيت الكود على جهاز مختلف

## Part 6: Linear Algebra & Matrix Operations (2 Questions)

#### 1) Compute the determinant and inverse of a square matrix of your choice.

In [24]:
arr=np.array([[4,8],[9,5]])
arr=arr**2
print(arr)
print(np.linalg.det(arr))
print(np.linalg.inv(arr))


[[16 64]
 [81 25]]
-4783.999999999999
[[-0.00522575  0.01337793]
 [ 0.01693144 -0.00334448]]


#### 2) What is the difference between:

- element-wise multiplication

- matrix multiplication
in NumPy?

In [25]:
#element-wise multipulation:
#دى يعنى كل عنصر فى المصفوفة الأولى هيتضرب فى العنصر اللى موجود فى نفس المكان فى المصفوفة التانية 
# matrix multiplication in Numpy:
# يعنى يضرب صف فى عمود 

## Bonus (Optional – Mindset Question)

#### How does NumPy help a Data Analyst think in a vectorized and mathematical way instead of a procedural one?

In [27]:
#بتسهل عليه الكود وبتخليه قصير ومش مستخدم فيه
#loops كتير
#وبتخلى الكود أسرع فى التنفيذ
